### ISSUE TITLE
Design Server Stats Dashboard

### ISSUE THREAD

**Issue by dimasciput** [kartoza/GeoHosting#101]
Create a user-friendly page to display server statistics, including:

- Real-time CPU usage chart
- Memory usage chart
- Server specifications overview
- Online status
- etc

@LenevJ, could you please look into the internet, for example?

**Comment by dimasciput** [comment]
Something like this maybe? 

![image](https://github.com/user-attachments/assets/ef75d7bf-e4ab-49a7-85b1-14b3b69ef93d)

**Comment by LenevJ** [comment]
@dimasciput I had a bit of trouble finding stats dashboards to reference and look at online, but I tried looking at my Laptop dashboard info and took some inspiration from there. 

I also considered how someone would access these stats if they have more than one product. That is why there is a text button navigation  Hosted Service / GeoSight Product at the top of the dashboard. (Please let me know if I should disregard such a feature for the time being)

I also tried to think how a person would be able to upgrade elements from their specific product or perhaps troubleshoot/inspect their product, hence the Upgrades/Updates/System Health in the first rectangle.

I would really appreciate some direction and feedback, because I feel like I am designing a bit blind at the moment and trying to anticipate for things that I am not sure are features etc.

![Stats Dashboard](https://github.com/user-attachments/assets/35d4aede-094e-4daa-837f-cab0c8b05249)

**Comment by meomancer** [comment]
Duplication of https://github.com/kartoza/GeoHosting/issues/133
