### ISSUE TITLE
Improve overview page

### ISSUE THREAD

**Issue by dimasciput** [kartoza/GeoHosting#66]
Improve the dashboard layouts.

Current dashboard in the staging site : 

https://geohosting.sta.do.kartoza.com/#/app/BIMS

![image](https://github.com/user-attachments/assets/0153cd93-60b1-4a0c-ba35-24e3fb0aea20)

**Comment by LenevJ** [comment]
@dimasciput I used the outline background idea (just made the lines thicker) and worked on changing the pricing displays. I looked at how different subscription sites did theirs and implemented elements. 

Things that I saw:
1. When there is more than one pricing option, the "GET THIS PLAN" buttons are different, the "best plan" usually has a button that is filled while other 2 (or more) options are just outlined buttons.
2. Most pricing plans have white as the holding shape colour and make use of either a slight outline or dropshadow to create visual contrast.

I left one of the pricing plan options the original grey just so we can compare the two options we have. I also changed the round buttons to rounded corner ones, since nowhere else on the website do we use a rounded button. I will change them back if we still want to use the round button option
<img width="1236" alt="Screenshot 2024-08-13 114329" src="https://github.com/user-attachments/assets/4ed19bf6-a711-4086-a09d-ef387b40df66">

**Comment by LenevJ** [comment]
@dimasciput I tried doing something different with the product information display. I felt it was a bit empty when there was only text and colours, so I tried creating icons to add that would help pull information together and be visually pleasing overall. I also played around with adding headings and breaking information up into "sections".

Everything can be changed, but I felt I needed to present as much at once so we can get a clearer picture of everything together.

What do you think of the two options at the bottom of the page (with the icons).

![Redesign Idea](https://github.com/user-attachments/assets/e55874e9-6982-4eb5-bb2a-7defea589c64)

**Comment by LenevJ** [comment]
@dimasciput I changed a few things around to see how it would look. 

Simplified icons to be like the ones on staging. Decided to use the grey holding shape. In the "What Can GeoSight Do For You?" section I decided to place everything within the blue so that it reads as a unit. I also added in the GitHub and Support writeups which I forgot about last time.

![Dashboard Option](https://github.com/user-attachments/assets/d0432f83-9996-49f7-9c27-e1018dbb96d6)

**Comment by dimasciput** [comment]
Thank you @LenevJ , I will assign Tinashe to update the overview page.

**Comment by LenevJ** [comment]
![Image](https://github.com/user-attachments/assets/ead5d51a-6f09-4308-bf33-a8a059a4c37b)
![Image](https://github.com/user-attachments/assets/a07ed89d-20f2-4125-a3e3-f977b62d83b3)
![Image](https://github.com/user-attachments/assets/a7b1cbc1-011e-4b96-8631-f7775e9e1a13)
![Image](https://github.com/user-attachments/assets/190198b7-dc66-4e62-ae80-4fa00aed67ca)
![Image](https://github.com/user-attachments/assets/69ffa748-2075-46fe-b317-b6390d2911d8)
