### ISSUE TITLE
Update Navigation Bar

### ISSUE THREAD

**Issue by dimasciput** [kartoza/GeoHosting#91]
We need to update the navigation bar to improve the user experience by making all projects accessible directly from the navigation bar without requiring the user to return to the homepage. 

### Display All Projects:

- Add all projects to the navigation bar.
- Consider grouping projects to avoid overcrowding the navbar.

### Design a responsive navigation bar layout for mobile devices.

- Ensure it is user-friendly and functional on smaller screens.

### Implement a feature that provides a brief overview of each project when the user hovers over it in the navigation bar.
- The overview could include project name, brief description, and status (optional).

**Comment by LenevJ** [comment]
@dimasciput Navbar development progress: Added all items to the navbar, it looks a lot better now that there is more items on it and it helps create visual balance between the main Kartoza navbar and this one. 

There are 2 options but the main difference is having a Home menu option as well to take the user back to the GeoHosting landing page, because currently there isn't a visible option (logo takes back to main website).
<img width="599" alt="Screenshot 2024-08-20 092826" src="https://github.com/user-attachments/assets/8bbaee64-b9c4-4914-8a0b-f9a0a99cb068">

**Comment by LenevJ** [comment]
Then I have to possible options for the mobile navbar. This one is based on what the current website navbar does when viewed on mobile. I added the orange highlighting of text and some lines just to help user see that their action (selecting option) is successful. I also think it is important for us to keep the option highlighted (on desktop version as well) so that the user knows exactly where they are at all times. 

Option 1:
![iPhone 13   14 - 2](https://github.com/user-attachments/assets/40c5d453-0003-43a1-bff4-568e94f64187)

Option 2:

What I like about this option is that it doesn't make the entire page content move down to accommodate the menu, but rather it moves over the content while also leaving a part of the screen available for the user to click back onto the page. Additional exiting option is the "x" button at the top of the menu
![iPhone 13   14 - 1](https://github.com/user-attachments/assets/78eedaa6-2ef6-49c0-b558-88fcd5f4db34)

**Comment by dimasciput** [comment]
@LenevJ You can remove the cart option for now; we don't need it. I think we can also remove "Home." Users should be able to go back by clicking the Kartoza icon on the top left. Let's simplify "Create Account" and "Sign In" to just "My Account." When a user clicks "My Account," it will show the login form, with a link to create a new account. Please see the current version in staging/dev.

If you put all of the items on the navbar, what will happen if we add more items in the future? I think it will overcrowd the navbar.

**Comment by LenevJ** [comment]
@dimasciput I applied your feedback in the following way: Created a GeoProduct related "category" with a drop down menu option to free up more space on the navbar. Also removed the cart as well as the Login and Sign Up buttons.

I added a search function as an option (tried mirroring the Kartoza website) on the navbar just to see how it would fit on desktop and mobile view. Will remove if we never plan on adding a search function.

![Navbar Options](https://github.com/user-attachments/assets/8d66a581-c503-43c2-ae32-4db6bf5409de)
